import { useRef } from "react";
import Lottie, { LottieRefCurrentProps } from "lottie-react";
import confetti from "./confetti.json";
import PrimaryButton from "../common/primaryCta";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
} from "../ui/dialog";

export default function LevelCompleteOverlay({
  isOpen,
  onClose,
  onReset,
  nextLevel,
}: {
  isOpen: boolean;
  onClose: () => void;
  onReset: () => void;
  nextLevel: string;
}) {
  const lottieRef = useRef<LottieRefCurrentProps>(null);

  if (!isOpen) return null;

  return (
    <div className="absolute top-0 left-0 w-full h-screen z-[1000] bg-black/80 flex flex-col items-center justify-center">
      {/* Confetti Animation Background */}
      <Lottie
        animationData={confetti}
        lottieRef={lottieRef}
        loop={true}
        onLoopComplete={async () => {
          lottieRef.current?.pause();
          await new Promise((resolve) => setTimeout(resolve, 5000));
          lottieRef.current?.play();
        }}
        style={{
          minHeight: "100vh",
          zIndex: 1010,
          pointerEvents: "none",
        }}
        rendererSettings={{
          preserveAspectRatio: "xMidYMid slice",
        }}
      />

      <Dialog open={isOpen} onOpenChange={onClose}>
        <DialogContent
          showCloseButton={false}
          className="z-[1000] md:max-w-lg gap-0 border-0 bg-white rounded-3xl shadow-2xl px-4 py-8 md:px-6 md:py-12 md:mx-4 text-center flex flex-col items-center"
        >
          <DialogHeader>
            <div className="w-20 h-20 bg-primary rounded-full flex items-center justify-center mx-auto mb-8">
              <svg
                className="w-10 h-10 text-white"
                fill="none"
                stroke="currentColor"
                viewBox="0 0 24 24"
              >
                <path
                  strokeLinecap="round"
                  strokeLinejoin="round"
                  strokeWidth={3}
                  d="M5 13l4 4L19 7"
                />
              </svg>
            </div>
            <DialogTitle className="text-4xl font-bold text-gray-900 mb-3">
              Level Complete!
            </DialogTitle>
          </DialogHeader>
          <DialogDescription className="text-lg text-gray-600 mb-10 leading-relaxed max-w-md">
            Outstanding performance! You&apos;ve mastered this challenge.
          </DialogDescription>

          <div className="flex flex-col md:flex-row gap-4">
            <PrimaryButton onClick={onReset} className="py-8">
              Play Again
            </PrimaryButton>

            <PrimaryButton href={nextLevel} className="">
              Next Level
            </PrimaryButton>
          </div>

          <p className="text-sm mt-8 text-gray-600 leading-relaxed px-2 max-w-md">
            By clicking on Play Again, you will also be able to see the code
            that was generated by you.
          </p>
        </DialogContent>
      </Dialog>
    </div>
  );
}
