import React, { useEffect, useRef } from "react";
import Lottie, { LottieRefCurrentProps } from "lottie-react";
import confetti from "./confetti.json";
import PrimaryButton from "../common/primaryCta";
import Link from "next/link";

export default function LevelCompleteOverlay({
  onReset,
  nextLevel,
}: {
  onReset: () => void;
  nextLevel: string;
}) {
  const lottieRef = useRef<LottieRefCurrentProps>(null);

  return (
    <div className="absolute top-0 left-0 w-full h-screen z-[1000] bg-black/80 flex flex-col items-center justify-center">
      {/* Confetti Animation Background */}
      <Lottie
        animationData={confetti}
        lottieRef={lottieRef}
        loop={true}
        onLoopComplete={async () => {
          lottieRef.current?.pause();
          await new Promise((resolve) => setTimeout(resolve, 5000));
          lottieRef.current?.play();
        }}
        style={{
          minHeight: "100vh",
          zIndex: 1010,
          pointerEvents: "none",
        }}
        rendererSettings={{
          preserveAspectRatio: "xMidYMid slice",
        }}
      />

      <div className="absolute inset-0 z-[1001] flex flex-col items-center justify-center px-4">
        <div className="absolute top-0 left-0 w-full h-screen z-[1000] flex flex-col items-center justify-center">
          <div className="bg-white rounded-3xl shadow-2xl px-4 py-8 md:px-6 md:py-12 mx-4 text-center flex flex-col items-center">
            {/* Success Icon */}
            <div className="w-20 h-20 bg-primary rounded-full flex items-center justify-center mx-auto mb-8">
              <svg
                className="w-10 h-10 text-white"
                fill="none"
                stroke="currentColor"
                viewBox="0 0 24 24"
              >
                <path
                  strokeLinecap="round"
                  strokeLinejoin="round"
                  strokeWidth={3}
                  d="M5 13l4 4L19 7"
                />
              </svg>
            </div>

            {/* Main Title */}
            <h1 className="text-4xl font-bold text-gray-900 mb-3">
              Level Complete!
            </h1>

            {/* Subtitle */}
            <p className="text-lg text-gray-600 mb-10 leading-relaxed max-w-md">
              Outstanding performance! You've mastered this challenge.
            </p>

            {/* Action Buttons */}
            <div className="flex flex-col md:flex-row gap-4">
              <PrimaryButton onClick={onReset} className="py-8">
                Play Again
              </PrimaryButton>

              <PrimaryButton href={nextLevel} className="">
                Next Level
              </PrimaryButton>
            </div>

            <p className="text-sm mt-8 text-gray-600 leading-relaxed px-2 max-w-md">
              By clicking on Play Again, you will also be able to see the code
              that was generated by you.
            </p>
          </div>
        </div>
      </div>
    </div>
  );
}
